name: null
favicon: null
layout_spectrum: 0.71656
typography_spectrum: 0.26338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e6dcc1'
    - '#a49261'
    - '#761b31'
    - '#956572'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: e270a589-8be0-45e3-8e8f-dc975cc013ca
    url: null
