name: null
favicon: null
layout_spectrum: 0.85526
typography_spectrum: 0.23039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111215'
    - '#8c755f'
    - '#eae7de'
    - '#edb073'
    - '#c02321'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: e270a589-8be0-45e3-8e8f-dc975cc013ca
    url: null
