name: null
favicon: null
layout_spectrum: 0.25367
typography_spectrum: 0.23039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0cfe6'
    - '#9eabb3'
    - '#5b749d'
    - '#e9b159'
    - '#3d4a54'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: e270a589-8be0-45e3-8e8f-dc975cc013ca
    url: null
