name: null
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#faf8f4'
    - '#2d2d25'
    - '#6a6350'
    - '#b1ad9e'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
