name: null
favicon: null
layout_spectrum: 0.5092
typography_spectrum: 0.26338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a79486'
    - '#7f3d3d'
    - '#927567'
    - '#312422'
    - '#394f44'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: e270a589-8be0-45e3-8e8f-dc975cc013ca
    url: null
