name: Chasing Saturday
favicon: null
layout_spectrum: 0.1112
typography_spectrum: 0.30686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ead3a8'
    - '#d23640'
    - '#6d6568'
    - '#151515'
    - '#e39095'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: e270a589-8be0-45e3-8e8f-dc975cc013ca
    url: null
