name: null
favicon: null
layout_spectrum: 0.25367
typography_spectrum: 0.23039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d4d1'
    - '#b0afaf'
    - '#44443c'
    - '#826954'
    - '#977f67'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: e270a589-8be0-45e3-8e8f-dc975cc013ca
    url: null
